name: wfiskymatch
channels:
  - conda-forge
  - defaults
  - astropy
dependencies:
  - astropy>=5.3.4
  - matplotlib>=3.10
  - numpy>=1.26.0
  - pip>=23.3
  - python>=3.12
  - scipy>=1.11.4
  - healpy>=1.18.0
  - jupyterlab>=4.0.11
  - asdf>=4.1.0
  - hpgeom>=1.4.0
  - healsparse>=1.11.1
  - skyproj>=2.0.0
  - h5py>=3.12.1
  - reproject>=0.14.1
  - pyvo>=1.5.2
  - statsmodels>=0.14.6
  - pip:
      - stsci.skypac==1.0.10
      - roman-datamodels>=0.23.1
      - maskfill>=1.1.1